workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get

      - name: Build iOS app for Simulator
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/*.app
